CREATE TABLE IF NOT EXISTS user (
  id    VARCHAR(36) PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(60) NOT NULL,
  name VARCHAR(20) NOT NULL,
  user  VARCHAR(20) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);